# Generated by Django 5.0.3 on 2024-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profit_alter_category_options_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='total_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
