# Generated by Django 5.0.3 on 2024-04-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profit_date_alter_profit_total_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
